[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/dashboard.html"
  status = 302

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
